version: '3'

services :
          app:
             build: .
             command: python manage.py runserver 127.0.0.1:8000
             ports:
                  - 8000:8000
             image: generative_ai
             container_name: generative-container