# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - docker-con

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6f8f5059e1c6488481386ea2ca4a43f6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0f716882ae8b46b5a986e6f14c40b34f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6f8f5059e1c6488481386ea2ca4a43f6 }}/generative_ai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'docker-con'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e4531402d610411abc363efa6343c696 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6f8f5059e1c6488481386ea2ca4a43f6 }}/generative_ai:${{ github.sha }}'